export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  sendGridApiKey: process.env.SENDGRID_API_KEY ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  zoomClientId: process.env.ZOOM_CLIENT_ID ?? "",
  zoomClientSecret: process.env.ZOOM_CLIENT_SECRET ?? "",
  zoomAccountId: process.env.ZOOM_ACCOUNT_ID ?? "",
  teamsClientId: process.env.TEAMS_CLIENT_ID ?? "",
  teamsClientSecret: process.env.TEAMS_CLIENT_SECRET ?? "",
  teamsTenantId: process.env.TEAMS_TENANT_ID ?? "",
  videoProvider: process.env.VIDEO_PROVIDER ?? "none",
};
